# Generated by Django 3.2.4 on 2021-08-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='number_of_pingbacks',
        ),
        migrations.AddField(
            model_name='entry',
            name='number_of_lpingbacks',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
