# Generated by Django 3.2.4 on 2021-08-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Can_v', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
