# Generated by Django 3.2.4 on 2021-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Can_v', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
