# Generated by Django 3.2.4 on 2021-08-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0002_auto_20210811_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
