# Generated by Django 3.2.4 on 2021-08-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0003_musician_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='musician',
            name='name',
        ),
    ]
