# Generated by Django 3.2.4 on 2021-08-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0004_auto_20210811_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='L', max_length=1),
            preserve_default=False,
        ),
    ]
