# Generated by Django 3.2.4 on 2021-08-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0009_auto_20210814_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personel',
        ),
    ]
