# Generated by Django 3.2.4 on 2021-08-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0011_place_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default="Bob's Cafe", max_length=50),
            preserve_default=False,
        ),
    ]
