# Generated by Django 3.2.4 on 2021-08-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0012_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='guy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Myguy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lethal.guy',),
        ),
    ]
