# Generated by Django 3.2.4 on 2021-08-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0013_guy_myguy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myguy',
        ),
        migrations.CreateModel(
            name='My_guy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lethal.guy',),
        ),
    ]
