# Generated by Django 3.2.4 on 2021-08-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0014_auto_20210815_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='guy',
            new_name='Partner',
        ),
        migrations.DeleteModel(
            name='My_guy',
        ),
        migrations.CreateModel(
            name='MyPartner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lethal.partner',),
        ),
    ]
