# Generated by Django 3.2.4 on 2021-08-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0015_auto_20210815_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='MyPartner',
        ),
    ]
