# Generated by Django 3.2.4 on 2021-08-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0016_auto_20210815_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
