# Generated by Django 3.2.4 on 2021-08-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0018_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='guy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='My_guy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lethal.guy',),
        ),
    ]
