# Generated by Django 3.2.4 on 2021-08-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0019_guy_my_guy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_guy',
        ),
    ]
