# Generated by Django 3.2.4 on 2021-08-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lethal', '0020_delete_my_guy'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_guy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Lethal.guy',),
        ),
    ]
