# Generated by Django 3.2.4 on 2021-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
