# Generated by Django 3.2.4 on 2021-07-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_sales_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='featured',
            field=models.BooleanField(null=True),
        ),
    ]
