# Generated by Django 3.2.4 on 2021-07-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_sales_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
