# Generated by Django 3.2.4 on 2021-07-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_alter_sales_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='summary',
            field=models.TextField(),
        ),
    ]
