# Generated by Django 3.2.4 on 2021-07-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_sales_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
