# Generated by Django 3.2.4 on 2021-07-26 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_auto_20210726_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='summary',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
