# Generated by Django 3.2.4 on 2021-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_alter_sales_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='summary',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
