# Generated by Django 3.2.4 on 2021-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_alter_sales_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10000),
        ),
    ]
