# Generated by Django 3.2.4 on 2021-07-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_alter_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.IntegerField(verbose_name=100),
        ),
    ]
