# Generated by Django 3.2.4 on 2021-07-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0013_alter_sales_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
    ]
